import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Raleway } from "next/font/google"
import "./globals.css";
import Navbar from "@/components/global/header";

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-raleway",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Saved By Divine Grace Ministry",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <Navbar />
     <html lang="en" className={raleway.variable}>
            <body className={raleway.className}>
{children}</body>
    </html>
    </>
  );
}
